apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: nest_app_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_NAME: nest_app_test
