apiVersion: batch/v1
kind: Job
metadata:
  name: nest-app-test-migrations
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: ebrizha/nest-app-test:IMAGE_TAG
          command: ["npm","run","migration:run"]

          envFrom:
            - secretRef:
                name: postgres-secret

      restartPolicy: Never
