name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout Helm chart
        uses: actions/checkout@v3
        with:
          repository: ebrizha/env-app-test
          path: helm-chart

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci
      - run: npm test
      - run: npm run build

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          docker build -t ebrizha/nest-app-test:${{ github.sha }} \
                       -t ebrizha/nest-app-test:latest .

      - name: Push image
        run: |
          docker push ebrizha/nest-app-test:${{ github.sha }}
          docker push ebrizha/nest-app-test:latest

      - name: Deploy with Helm
        run: |
          helm upgrade --install app ./helm-chart/app-chart \
            --set nestApp.image.tag=${{ github.sha }} \
            --reuse-values \
            --rollback-on-failure \
            --timeout 5m
